### PR TITLE
CSS selectors instead of XPath

### PR DESCRIPTION
**Pull request by jnothman**
CSS selectors have the benefit of looking simpler and being more tuned to HTML (e.g. matching classes correctly is hard in XPath). They are also supported by the user-friendly (but not DOM-compatible in its naming) BeautifulSoup, while XPath is not.

Standard CSS selectors are not, however, as powerful as XPath, as described in the "Limitations of CSS Selectors" section. In web scraping, one is more often forced to rely on a general purpose programming language with CSS selectors than with XPath.

### CODE REVIEW

**Comment by jnothman** [comment]
Note merging this would this content inconsistent with the later lessons, which assume XPath.

**Comment by jnothman** [comment]
Note merging this would make this content inconsistent with the later lessons, which assume XPath.

@richyvk may be interested in the limitations of CSS selectors and their presentation.

**Comment by weaverbel** [comment]
Could we offer this a separate option rather than a replacement? @jnothman @timtomch

**Comment by jnothman** [comment]
I'd like to, yes, but I'm not sure how to do that structurally within the lesson template. If I have two separate episodes, the time is added up on the front page. I could have two headings within one page, if that's better, but I'm not sure it is.

**Comment by richyvk** [comment]
Just to throw something else in the mix, had a gerat chat with @elliewix and @elainewong today about the Python lesson. Part of the discuss went a bit broader and we talked about possible future lessons to come of the back of the python intro. One was parsing xml with XPATH and the other was a sort of beautifulSoup v xpath/lxml battle. We talked about the overlap with the scraping lesson, but the consensus was they are sloghtly different things - scraping vs parsing xml that is. So, that might happen...

**Comment by jnothman** [comment]
Unless you're going to teach XQuery/XSLT, I don't actually think they're different enough things to be worth maintaining a separate workshop. They're both about identifying fragments of a document that are of interest, sometimes following through to different documents (or API calls), and extracting them into CSV/JSON/RDBMS.

The major things you get a lot of in XML that do not affect HTML so much are namespaces and validation issues.

**Comment by timtomch** [comment]
@kimpham54 what do you think are the pros and cons of CSS selectors vs XPath in the context of web scraping?
I personally don't feel strongly one way or another. If we decide to use CSS selectors instead, I would suggest we stick to it for the entire lesson. That means, we need to rewrite the entire XPath episode.
Also I'm not sure about maintaining both a CSS and an XPath version, might be hard to keep current. Better choose one and stick to it.

**Comment by richyvk** [comment]
@jnothman you'd have to talk to Elizabeth and Elaine about that, but they were both pretty certain that a lesson on parsing xml could be a worthwhile thing to have as a separate thing to this lesson.

**Comment by jnothman** [comment]
@timtomch, this pull request basically does that rewriting of the XPath episode for CSS.

Re CSS selectors:
* Pro: tuned to HTML: getting whitespace-delimited `class`es and even `itemprop`s is easy and legible.
* Pro: tuned to HTML: case-insensitive by default.
* Pro: skills are portable to/from basic web dev.
* Pro: lots of people find XPath a bit scary/confusing and hard to debug. But I think that's partially because it uses slashes as delimiters, sometimes meaning "child of previous" and sometimes meaning "relative to previous"
* Con: XPath is strictly more expressive (in the current supported versions). CSS particularly lacks in being able to extract something on the basis of what it contains.
* Con?: CSS can't extract text or attribute values
* Con: AFAIK, there isn't a standard way to express relative expressions, e.g. given an element, get that element's children
* Con: the above means the user of CSS Selectors is often forced to fall back to DOM traversal in their general programming language, while a user of XPath may choose to do everything in absolute/relative XPath.
* Con: participants who know CSS might be bored of learning it again

**Comment by kimpham54** [comment]
@timtomch @jnothman XPath is relevant to librarians working with catalogue and other metadata records, but I agree that in the context of web scraping that using CSS selectors is more in line with html/web standards. No issue with using CSS selectors instead of XPath here.

**Pull request merged**
