### PR TITLE
Rewritten episodes; scraping UNSC resolutions

### PR DESCRIPTION
**Pull request by jnothman**
I now have episodes on CSS selectors, using the Web Scraper browser extension, and using python requests/lxml drafted for presentation this coming Monday.

I'm torn on providing the browser extension module. I advised that there would not be a hard requirement on Python knowledge. I also feel that visually is how most people scrape these days.

But I also suspect it'll be quite tight for time. I'm not sure how to estimate times for this kind of lesson (as opposed to a deck of slides). Comment on that would be welcome.

I'd particularly appreciate comments on intelligibility/accessibility from people without software engineering backgrounds. But I understand that I should expect at most a skim review given the lack of time.

Thanks!

(No merge required. This branch is rendered at https://ctds-usyd.github.io/library-webscraping/)

### CODE REVIEW

**Comment by ldko** [comment]
I read over the Introduction and the CSS Selectors lessons  (I am impressed by how much work you have done on all of this in a short amount of time). I do have a software development background, so I am not the ideal person to give feedback, but I work on the backend mostly and don't directly work with navigating HTML, JavaScript, CSS, DOM much. Also, I have barely used the JavaScript console. The two episodes I read were clear to me, and I thought the parts with JavaScript console are well-designed. A couple things that stood out to me in the CSS selectors episode:
1. Under `Tree Structure`, with talking about the hierarchical structure of parent/child/descendant/sibling/path do you think it would be worth tying back the definitions of those hierarchies to the diagram above more explicitly or possibly having a separate diagram that visualizes the hierarchy of terms? For instance saying something like how in the diagram above, the Attribute: type=basic and the Elements:`manufacturer`, `contact`, and `date` are all siblings whose parent is the root element...etc. (or maybe it is implied that an instructor would do this without it being explicitly written out in the episode?)
2. In the ` Select the "Matching patterns" title by ID` and the `Select this challenge box text`, maybe the information given as _Tips_ would make sense to include outside/before the challenge boxes in the main content of the `Class and ID filtering` section?

I haven't looked at the rest of the lesson re-design changes yet, but what I have seen looks great @jnothman :+1:

**Comment by jnothman** [comment]
Thanks, Lauren!

**Comment by weaverbel** [comment]
Feel free to ping me to do merges @jnothman - not sure which bits need merging and which bits not.

**Comment by jnothman** [comment]
I'll present it from my branch on Monday, so no need to merge until after
then. Thanks for catching the typo, and for the general attention,
@weaverbel

**Pull request closed without merging**
